name: titipbarang_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  device_info_plus: ^11.1.1
  device_preview: ^1.2.0
  dio: ^5.7.0
  easy_refresh: ^3.4.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed_annotation: ^2.4.4
  get: ^4.6.6
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  m_widget:
    git:
      url: https://github.com/BlastTea/MWidget.git
      ref: 309f46d45153ee8fbf3d50d617575ba31599a959
  package_info_plus: ^8.1.1
  path_provider: ^2.1.5
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.4.1
  universal_io: ^2.2.2
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_gen:
  output: lib/resources/
  integrations:
    rive: true
