final Map<String, String> enUs = {
  'txt_offline': 'You are offline',
  'txt_error': 'Oops, there was an error!',
  'txt_ok': 'Ok',
  'txt_language_english': 'English',
  'txt_language_indonesian': 'Bahasa Indonesia',
  'txt_an_error_occured': 'An error occured',
  'txt_retry': 'Retry',
  'txt_no_data': 'No data',
  'txt_url_not_found': 'URL not found, please update the application',
  'txt_internal_server_error': 'An error occurred on the server',
  'txt_failed_connect_to_server': 'Failed to connect to server, please check your internet connection',
  'txt_pull_to_refresh': 'Pull to refresh',
  'txt_realease_ready': 'Release ready',
  'txt_refreshing': 'Refreshing...',
  'txt_succeeded': 'Succeeded',
  'txt_no_more': 'No more',
  'txt_last_updated_at': 'Last updated at %T',
  'txt_fetching_data': 'Fetching data...',
  'txt_sign_in': 'Sign in',
  'txt_username': 'Username',
  'txt_empty_username': 'Username is still empty',
  'txt_password': 'Password',
  'txt_empty_password': 'Password is still empty',
  'txt_home': 'Home',
  'txt_history': 'History',
  'txt_profile': 'Profile',
  'txt_welcome': 'Welcome, %s',
  'txt_dark_mode': 'Dark mode',
  'txt_sign_out': 'Sign out',
};
