final Map<String, String> idId = {
  'txt_offline': 'Anda sedang offline',
  'txt_error': 'Ups, ada kesalahan!',
  'txt_ok': 'Ok',
  'txt_language_english': 'English',
  'txt_language_indonesian': 'Bahasa Indonesia',
  'txt_an_error_occured': 'Terjadi kesalahan',
  'txt_retry': 'Coba lagi',
  'txt_no_data': 'Tidak ada data',
  'txt_url_not_found': 'URL tidak ditemukan, silahkan update aplikasi',
  'txt_internal_server_error': 'Terjadi error di server',
  'txt_failed_connect_to_server': 'Gagal terhubung ke server, silahkan periksa koneksi internet Anda',
  'txt_pull_to_refresh': 'Tarik untuk menyegarkan',
  'txt_realease_ready': 'Siap rilis',
  'txt_refreshing': 'Menyegarkan...',
  'txt_succeeded': 'Berhasil',
  'txt_no_more': 'Tidak ada lagi',
  'txt_last_updated_at': 'Terakhir diperbarui pada %T',
  'txt_fetching_data': 'Mengambil data...',
  'txt_sign_in': 'Masuk',
  'txt_username': 'Username',
  'txt_empty_username': 'Username masih kosong',
  'txt_password': 'Kata sandi',
  'txt_empty_password': 'Kata sandi masih kosong',
  'txt_home': 'Beranda',
  'txt_history': 'Riwayat',
  'txt_profile': 'Profil',
  'txt_welcome': 'Selamat datang, %s',
  'txt_dark_mode': 'Tema gelap',
  'txt_sign_out': 'Keluar',
  'txt_skip': 'Lewati',
};
